package net.minecraft.src;

public class GenLayerRiverMix extends GenLayer
{
    private GenLayer biomePatternGeneratorChain;
    private GenLayer riverPatternGeneratorChain;

    public GenLayerRiverMix(long par1, GenLayer par3GenLayer, GenLayer par4GenLayer)
    {
        super(par1);
        this.biomePatternGeneratorChain = par3GenLayer;
        this.riverPatternGeneratorChain = par4GenLayer;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long par1)
    {
        this.biomePatternGeneratorChain.initWorldGenSeed(par1);
        this.riverPatternGeneratorChain.initWorldGenSeed(par1);
        super.initWorldGenSeed(par1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int xOffset, int zOffset, int xSize, int zSize)
    {
        int[] biomeInts = this.biomePatternGeneratorChain.getInts(xOffset, zOffset, xSize, zSize);
        int[] riverInts = this.riverPatternGeneratorChain.getInts(xOffset, zOffset, xSize, zSize);
        int[] intCache = IntCache.getIntCache(xSize * zSize);

        for (int var8 = 0; var8 < xSize * zSize; ++var8)
        {
            if (biomeInts[var8] == BiomeGenBase.ocean.biomeID)
            {
                intCache[var8] = biomeInts[var8];
            }
            else if (riverInts[var8] >= 0)
            {
            	// SCADDON: replaced below
//                if (biomeInts[var8] == BiomeGenBase.icePlains.biomeID)
//                {
//                    intCache[var8] = BiomeGenBase.frozenRiver.biomeID;
//                }
            	
            	// SCADDON: added
                if (SCBiomeConfiguration.getRiverVariantForBiomes(biomeInts[var8]) != -1)
                {
                	intCache[var8] = SCBiomeConfiguration.getRiverVariantForBiomes(biomeInts[var8]);
                }
                // END SCADDON
                else if (biomeInts[var8] != BiomeGenBase.mushroomIsland.biomeID && biomeInts[var8] != BiomeGenBase.mushroomIslandShore.biomeID)
                {
                    intCache[var8] = riverInts[var8];
                }
                else
                {
                    intCache[var8] = BiomeGenBase.mushroomIslandShore.biomeID;
                }
            }
            else
            {
                intCache[var8] = biomeInts[var8];
            }
        }

        return intCache;
    }
}
